### ISSUE TITLE
sqlite db locking

### ISSUE THREAD

**Issue by funkymrrogers** [funkymrrogers/acd-backups#5]
15-12-14 23:04:55.739 [CRITICAL] [acdcli.cache.db] - Error opening database: (sqlite3.OperationalError) database is locked [SQL: 'PRAGMA table_info("metadata")']
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/base.py", line 1139, in _execute_context
    context)
  File "/usr/lib64/python3.4/site-packages/sqlalchemy/engine/default.py", line 450, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: database is locked

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/bin/acd_cli.py", line 1429, in <module>
    main()
  File "/usr/bin/acd_cli.py", line 1399, in main

**Comment by funkymrrogers** [comment]
As best I can tell this is related to concurrent backups leveraging acdcli. Going to serialize the multiple backup scripts that are setup in the testbed and commit fix.

To be clear above error is posted when no other processes are running, after db is stuck locked.

**Comment by funkymrrogers** [comment]
00 \* \* \* \* flock -n /root/backup-scripts/movies.lock flock /root/backup-scripts/serial.lock -c /root/backup-scripts/movies.sh - adding in a flock that will wait seems to work, and on the current kernel appears to work in order that processes were blocked.

**Comment by funkymrrogers** [comment]
Fixed by https://github.com/funkymrrogers/acd-backups/commit/1c74e99f7d8fe20eff1de233c7f03f4abf514a46
